### ISSUE TITLE
Investigate latest industry status (NFX303, ARC307)

### ISSUE THREAD

**Issue by r12f** [futurewei-cloud/alioth-app#1]

**Comment by r12f** [comment]
Hello world!

**Comment by r12f** [comment]
- https://www.youtube.com/watch?v=Xbn65E-BQhA
- https://www.youtube.com/watch?v=tm5GEePP1PY

**Comment by Fangjin98** [comment]
The status is summarized in [Feishu doc](https://cn287zbjkb.feishu.cn/wiki/wikcnTHZAh5oYlORmSrGOjSDgfd)
